import { Inter } from "next/font/google";
import "@/app/globals.css";

import { Providers } from "./providers";
import NavPage from "@/components/navPage";
import Footer from "@/components/footer";
import Background from "@/components/sections/background";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spurgeon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavPage />
          <Background />

          <main className="  mx-auto max-w-7xl px-6 lg:px-8">
            {children}
          </main>

          {/* <Background /> */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
